name: "Build the database and Upload"

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cat DBfiles and make DB
      uses: ./docker-action
