name: "Build the database and Upload"

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cat DBfiles and make DB
      uses: ./docker-action
    - name: Commit Changes
      uses: EndBug/add-and-commit@v5
      with: 
        author_name: FinnJaekel
        author_email: finn.jaekel@web.de
        message: "Add new DB"
        add: "testdb.db"
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Touch .nojekyll
      run: |
        mkdir db
        mv testdb.db db/
        touch db/.nojekyll
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./db
        force_orphan: true
